[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
itertools = "0.10.0"
console_error_panic_hook = "0.1.7"
regex = "1.5"
take-until = "0.1.0"
